# builder image
FROM node:22-slim as builder
ENV NODE_ENV build
RUN apt-get update && apt-get install -y openssl libssl-dev

# user node
USER node
WORKDIR /home/node

COPY package*.json ./
COPY prisma/ ./prisma/

RUN npm ci

COPY src/generated/.prisma ./node_modules/.prisma

COPY --chown=node:node . .

# build dist
RUN npm run build \
    && npm prune --omit=dev

# production image
FROM node:22-slim as production
RUN apt-get update && apt-get install -y openssl libssl-dev

# Create app directory
USER node
WORKDIR /home/node

# Copy packages
COPY --from=builder --chown=node:node /home/node/package*.json ./
COPY --from=builder --chown=node:node /home/node/node_modules/ ./node_modules/
COPY --from=builder --chown=node:node /home/node/dist/ ./dist/

EXPOSE 3000

CMD [ "npm", "run", "start:prod" ]