# builder image
FROM node:22-slim as builder
ENV NODE_ENV build
RUN apt-get update && apt-get install -y openssl libssl-dev

ENV DATABASE_URL postgresql://pogledaj_user:ovojesifrazabazu_pogledaj_db_dev@192.168.1.9:5432/pogledaj_db_dev

# user node
USER node
WORKDIR /home/node

COPY package*.json ./
COPY prisma/ ./prisma/

# build node_modules
RUN npm ci

RUN npx prisma generate --sql

COPY --chown=node:node . .

# build dist
RUN npm run build \
    && npm prune --omit=dev

# production image
FROM node:22-slim as development
RUN apt-get update && apt-get install -y openssl libssl-dev

# define ENV variables
ENV NODE_ENV development
ENV APP_LISTEN_PORT 8080
ENV DATABASE_URL postgresql://pogledaj_user:ovojesifrazabazu_pogledaj_db_dev@192.168.1.9:5432/pogledaj_db_dev
ENV SENDGRID_API_KEY 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
ENV AUTH_ADMIN_USER_JWT_SECRET ITK2fyevjvEMjlqmW99jNx3B2SFttZST5i9ra8Pkt5AFHqNB3Poqo3FGLzZ2J6j
ENV REDIS_URL redis://127.0.0.1:6379
ENV TMDB_V4_API_KEY=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2YjM3YTE0MmJlNWZjZmVhNjkxNDhiZmNhMDQ2MzEwMCIsInN1YiI6IjYzY2ZkOGQyMGQyZjUzMDFkOWE1YmRjMyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.sOAKTNTWGHSk9YPP6HKdOe3VLpndM1axW169nPpzRIE
ENV TMDB_V3_API_KEY=6b37a142be5fcfea69148bfca0463100

# Create app directory
USER node
WORKDIR /home/node

# Copy packages
COPY --from=builder --chown=node:node /home/node/package*.json ./
COPY --from=builder --chown=node:node /home/node/node_modules/ ./node_modules/
COPY --from=builder --chown=node:node /home/node/dist/ ./dist/

EXPOSE 8080

CMD [ "npm", "run", "start:prod" ]