# builder image
FROM node:16-slim as builder
ENV NODE_ENV build
RUN apt-get update && apt-get install -y openssl libssl-dev

# user node
USER node
WORKDIR /home/node

COPY package*.json ./
COPY prisma/ ./prisma/

# build node_modules
RUN npm ci

COPY --chown=node:node . .

# build dist
RUN npm run build \
    && npm prune --omit=dev

# production image
FROM node:16-slim as development
RUN apt-get update && apt-get install -y openssl libssl-dev

# Create app directory
ENV NODE_ENV production
ENV APP_LISTEN_PORT 8080
ENV DATABASE_URL postgresql://pogledaj_user:ovojesifrazabazu_pogledaj_db_dev@bruno.spdns.org:5432/pogledaj_db_dev

USER node
WORKDIR /home/node

# Copy packages
COPY --from=builder --chown=node:node /home/node/package*.json ./
COPY --from=builder --chown=node:node /home/node/node_modules/ ./node_modules/
COPY --from=builder --chown=node:node /home/node/dist/ ./dist/

EXPOSE 8080

CMD [ "npm", "run", "start:prod" ]