name: pogledajAPI CI

on:
  push:
    branches:
      - main
    paths:
      - apps/api/**
jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image
        run: |
          docker build -f ./apps/api/CI/Dockerfile-dev ./apps/api --tag ghcr.io/creepy00/pogledaj/pogledaj-api:latest
          docker push ghcr.io/creepy00/pogledaj/pogledaj-api:latest