name: publish
on:
  push:
    branches:
      - main
    paths:
      - apps/api/**
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the Docker image
run: |
       docker build -f ./apps/api/CI/Dockerfile/Dockerfile . --tag ghcr.io/creepy00/pogledaj/pogledajapi:latest
       docker run ghcr.io/creepy00/pogledaj/pogledajapi:latest
       docker push ghcr.io/creepy00/pogledaj/pogledajapi:latest