name: pogledajAPI Test Fly Deploy

on:
  push:
    branches:
      - main
    paths:
      - apps/api/**

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: test
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy ./apps/api --remote-only --config fly.test.toml