name: pogledajWeb CI

on:
  push:
    branches:
      - main
    paths:
      - apps/web/**
jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image
        run: |
          docker build -f ./apps/web/CI/Dockerfile ./apps/web --tag ghcr.io/goran-blazin/pogledaj/pogledaj-web:latest
          docker push ghcr.io/goran-blazin/pogledaj/pogledaj-web:latest